export const ADD_MOVIE = 'ADD_MOVIE';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE'; 

export const GET_MOVIE_BY_ID_SUCCESS = 'GET_MOVIE_BY_ID_SUCCESS';
export const MOVIE_BY_TITLE_SUCCESS = 'MOVIE_BY_TITLE_SUCCESS';
export const FIND_MOVIE = 'FIND_MOVIE';

export const ADD_USER = 'ADD_USER';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const SIGNOUT = 'SIGNOUT';

export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';
export const GET_COMMENT_BY_MOVIE_ID= 'GET_COMMENT_BY_MOVIE_ID';

export const ADD_LIKE= 'ADD_LIKE';
export const REMOVE_LIKE= 'REMOVE_LIKE';

export const GET_AUTHORIZED_USER= 'GET_AUTHORIZED_USER';
